---
version: "3.8"

services:
  web:
    build: .
    restart: 'on-failure'
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/skeletondb?createDatabaseIfNotExist=true'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'rootpassword'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: 'org.hibernate.dialect.MySQL5InnoDBDialect'
      SPRING_DATASOURCE_DRIVERCLASSNAME: 'com.mysql.cj.jdbc.Driver'

      #after the first initialization, the data will be only updated and not overwritten
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update

      #Initializing the database/volume (uncomment the lines, run it once, comment again)
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'update'
      SPRING_JPA_GENERATE_DDL: 'true'
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: 'true'
      SPRING_DATASOURCE_INITIALIZATION_MODE: 'always'
      MYSQL_HOST: 'db'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_PORT: '3306'
    depends_on:
      - 'db'
  db:
    image: 'mysql'
    environment:
      MYSQL_DATABASE: 'skeletondb'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3307:3306'
    volumes:
      - 'skeleton:/var/lib/mysql'
    expose:
      - '3306'
    cap_add:
      - 'SYS_NICE'

volumes:
  skeleton: 